linters-settings:
  goimports:
    # Separate internal packages from external
    local-prefixes: github.com/ribeirohugo/go_startup

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # from this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work
  # on Windows.
  skip-dirs:
    - vendor

  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 1

linters:
  # Enable extra linters besides the default ones
  enable:
    - deadcode
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gosec
        - lll
