name: Test and Lint
on:
  pull_request

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest

      - uses: actions/checkout@v2
      - name: tidy
        run: go mod tidy

      - name: Generate
        run: go generate ./...

      - name: Test
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          skip-pkg-cache: true
          skip-build-cache: true
